# -*- coding: utf-8 -*-
"""Efni handbókarinnar — kaflatextar Handbókar A (EFNI) og B (EFNI_B).

Heimildir: brunahönnun ÖRUGG 3749-001 (SKY-001 / SAT-001-V02), aðaluppdrættir
ARKÍS 23-076 (byggingarleyfissett 12.9.2025), verklýsing TEKNIK 24-085 (lagnir
og loftræsing), verklýsing Verkhönnunar (raflagnir, kafli 4), verksamningar og
efnissamþykktir í verkgagnagrunni. Óstaðfest atriði merkt [staðfesta].
"""

EFNI = {
 "K0": [
  ("Um handbókina",
   "Handbók þessi er handbók hússins (handbók mannvirkis) fyrir Hjúkrunarheimilið Hamranesi, Hringhamri 43, Hafnarfirði, unnin í samræmi við gr. 16.1.1 byggingarreglugerðar nr. 112/2012, leiðbeiningar HMS (liðir a–j) og staðalform FSRE fyrir handbók mannvirkis. Byggingarstjóri afhendir handbókina eiganda og byggingarfulltrúa á rafrænu formi fyrir lokaúttekt. Handbókin er tvískipt: Handbók A (hússins) er hin tæknilega skyldubók; Handbók B (eiganda) er leiðarvísir eiganda og rekstraraðila í daglegum rekstri. Kaflaheiti fylgja staðalformi FSRE (kaflar K0–K15 samsvara 1.0–1.15) og fjórir kaflar eru umfram staðalformið: K16 VBC-einingaskrá, K17 hússtjórnarkerfi, K18 ábyrgðir og K19 rekstraráætlun."),
  ("Notkunarleiðbeiningar",
   "Vefútgáfa handbókarinnar er aðgangsvarin og uppfærist sjálfvirkt úr verkgagnagrunni sem speglar Procore- og ACC-verkkerfi verksins tvisvar á dag; skrár hennar (aðilaskrá, uppdráttaskrá, efnissamþykktir, áfangaúttektir, VBC-einingaskrá) eru því alltaf í takt við verkið. Kaflar vísa hver í annan með tenglum og hverjum kafla fylgir gátlisti krafna. Prentútgáfa með efnisyfirliti fæst með „Sækja PDF“ hnappnum; hún er sú útgáfa sem afhent er formlega. Gátlistinn aftast í bókinni er lokunarlisti verksins: þar sést hvað vantar enn í handbókina og hver skilar því."),
  ("Almennar upplýsingar um verkið",
   "Hjúkrunarheimilið Hamranesi er hjúkrunarheimili með 96 hjúkrunarrýmum skv. gildandi byggingarleyfi (aðaluppdrættir ARKÍS nr. 23-076, byggingarleyfissett 12.9.2025; landeignanúmer 1231987) auk þjónustutengdrar starfsemi á jarðhæð [staðfesta lokafjölda rýma — fjölgun í 99 rými er háð breyttu aðalskipulagi, og brunahönnun V02 miðar við 88 íbúa að hámarki; samræma við lokaútgáfur]. Byggingin er fimm hæðir, sett saman úr forsmíðuðum rýmiseiningum (VBC) og hönnuð með algildri hönnun og BREEAM-umhverfisvottun að markmiði [staðfesta einkunn]. Megininngangur er um miðhluta byggingar; á jarðhæð eru stoðrými, starfsmannarými, tæknirými og fjölnotasalur, en hjúkrunarrými ásamt sameiginlegum rýmum á efri hæðum í norður- og suðurálmum. Heildarstærð er um 7.060 m² (A+B rými) [staðfesta m.v. lokaskráningartöflu]. Byggingin er í notkunarflokki 5 og brunaálag skal vera undir 800 MJ/m². Eigandi er Hjúkrunarheimilið Hamranesi ehf. (kt. 570424-1060); leigutaki er FSRE með 25 ára leigusamningi; rekstraraðili er Sóltún; byggingarstjórn er á hendi Ísfast ehf. Verklok eru áætluð snemma árs 2027."),
  ("Umhverfisáherslur",
   "Byggingin er hönnuð með hliðsjón af BREEAM-umhverfisvottunarkerfinu [staðfesta einkunn og vottunarstig við verklok]. Í BREEAM-kerfinu eru skilgreindar kröfur er varða m.a. innivist, orku- og vatnsnotkun, meðhöndlun úrgangs, aðstöðu fyrir gangandi og hjólandi og notkun efna. Forsmíðuð einingabygging dregur jafnframt úr byggingarúrgangi og röskun á byggingartíma. BREEAM-gögn verksins eru varðveitt í verkgagnagrunninum og vottunarskjöl fylgja lokaútgáfu handbókar."),
  ("Neyðarupplýsingar (drög)",
   "Brunaviðvörunarstöð er í aðalinngangi og undirstöðvar á hæðum. Sprinklerklefi er á jarðhæð, aðgengilegur utan frá; inndælingartengi og vatnsbjalla eru á útvegg. Þurrar stigleiðslur eru í öllum stigahúsum með tengingum slökkviliðs á hverri hæð og tengibúnaði við dælur slökkviliðs á jarðhæð. Handslökkvitæki eru 6L léttvatnstæki (slökkvigeta 21A/183B) í almennum rýmum og 5 kg CO2-tæki í tæknirýmum, staðsett skv. teikningum. Fyrsta stig rýmingar er lárétt milli brunahólfa innan hæðar. [Staðfesta og fylla inn: söfnunarstaðir utandyra, aðallokar neysluvatns og hitaveitu, aðalrofar rafmagns, tengiliðir neyðarþjónustu og bilanavaktar.]"),
  ("Afhending handbókar",
   "Handbókin er afhent skv. gr. 1.0.5 í staðalformi FSRE: byggingarstjóri, fulltrúi FSRE, byggingarfulltrúi, rekstraraðili og verktaki staðfesta móttöku og yfirferð með undirskriftum á afhendingarsíðu sem fylgir lokaútgáfu. Gátlisti staðalformsins (fylgiskjal 2.1) er undirritaður af verktaka við sömu afhendingu.")],
 "K1": [
  ("Verkkaupi og byggingarstjórn",
   "Verkkaupi og eigandi: Hjúkrunarheimilið Hamranesi ehf., kt. 570424-1060. Byggingarstjóri: Hallgrímur Magnússon, Ísfast ehf. (s. 666-4463, hallgrimur@isfast.is). Tengiliður verkkaupa gagnvart verktökum: Sveinn Björnsson, Ísfast ehf. Verkefnastjórn og byggingarstjórn er á hendi Ísfast ehf."),
  ("Hönnuðir",
   "Arkitektúr og hönnunarstjórn: ARKÍS arkitektar ehf. (aðaluppdrættir nr. 23-076, áritaðir af Viggó Magnússyni). Burðarvirki á staðnum: Hanna verkfræðistofa; burðarvirki VBC-eininga: WSP. Lagnir og loftræsing: TEKNIK verkfræðistofa (verklýsing 24-085). Raflagnir: Verkhönnun (verklýsing, kafli 4). Brunahönnun: ÖRUGG verkfræðistofa (nr. 3749-001). Hljóðvist: Myrra. Lóðarhönnun: Landslag."),
  ("Verktakar og birgjar",
   "Jarðvinna: Grafa og Grjót ehf. (verksamningur 14.11.2025). Uppsteypa/steypa: Steypustöðin. Múrverk: Múrverk og Slípun ehf. (20.3.2026). Pípulagnir: Rennsli ehf. (11.3.2026). Loftræsing: Ísloft blikk- og stálsmiðja ehf. Einingaframleiðsla: VBC (framleiðslusamningur með viðaukum); stálvirki eininga: Norvik Group. Lyftur: KONE (MonoSpace 700DX). Álhurðir og gluggar: BYKO; reyklúgur og aðgangslúga: BYKO. Netbúnaður: Origo. Sjúkrakallkerfi: Televik, birgir Öryggismiðstöðin. Aðrir samningsbundnir verktakar: Heildarverk ehf. og Steingarður ehf. [staðfesta verkhluta hvors]; rafverktaki [staðfesta]. Full aðilaskrá með tengiliðum er í skránni „Aðilaskrá“ og uppfærist sjálfvirkt úr verkkerfi."),
  ("Iðnmeistarar og þjónustuaðilar",
   "Skráðir iðnmeistarar verksins verða staðfestir m.v. skráningu hjá byggingarfulltrúa Hafnarfjarðar og birtir hér ásamt löggildingum [söfnun í gangi — sjá gátlista]. Þjónustuaðilar framtíðarrekstrar (brunaviðvörun, sprinkler, lyftur o.fl.) bætast við þegar þjónustusamningar hafa verið gerðir; undirritaðir þjónustusamningar eru skilyrði öryggisúttektar.")],
 "K2": [
  ("Um uppdráttaskrána",
   "Uppdráttaskrá handbókarinnar er unnin sjálfvirkt úr teikningaskrá verksins í Procore og telur nú 1.151 gildandi teikningu (1.737 útgáfur alls með útgáfusögu). Teikningasett skiptast í aðaluppdrætti (ARKÍS 23-076), verkteikningar hvers fagsviðs — burðarvirki (Hanna/WSP), lagnir og loftræsing (TEKNIK), raflagnir (Verkhönnun), brunavarnir (ÖRUGG), lóð (Landslag), hljóðvist (Myrra) — og framleiðsluteikningar VBC-eininga (MOD, MEP, burðarvirki, hurðir/gluggar, innréttingar) auk verkstæðisteikninga Norvik fyrir stálvirki."),
  ("Lokaútgáfur og reyndarteikningar",
   "Við verklok verða lokaútgáfur (reyndarteikningar) merktar sérstaklega í skránni og ábyrgðaraðili (hönnuður) tilgreindur á hverri línu skv. staðalformi FSRE, tafla 2. Reyndarteikningar skulu endurspegla byggð frávik frá útboðsgögnum; frávik eru rakin í gegnum fyrirspurnir (RFI) og breytingaskipanir sem varðveittar eru í verkgagnagrunninum.")],
 "K3": [
  ("Framvinda verksins",
   "Verkið hófst með jarðvinnu Grafa og Grjóts ehf. skv. verksamningi dags. 14.11.2025, ásamt lagnavinnu í jörðu og undirbyggingu. Rýmiseiningar eru framleiddar í verksmiðju VBC og fluttar á verkstað í tveimur meginlotum: lota 1 (50 einingar) afhent í september 2026 og lota 2 frá viku 12. október 2026. Uppsetningu fylgir samsetning og þétting á staðnum (zip-up) sem áhafnir VBC annast. Frágangsúttektir hefjast 9. nóvember 2026 og verklok eru áætluð snemma árs 2027, þá öryggisúttekt fyrir töku í notkun og lokaúttekt í kjölfarið."),
  ("Áfangaúttektir",
   "Áfangaúttektir eru framkvæmdar og skráðar í Procore og keyrðar á stafliði gr. 3.7.4 byggingarreglugerðar (jarðvinna, uppsteypa, stálvirki, hitalagnir, fráveitulagnir o.s.frv.). Skráðar eru 19 úttektir með 75 fylgiskjölum; 12 eru enn opnar — sjá sjálfvirkan lista í gátlistanum. Rýni byggingarfulltrúa Hafnarfjarðar á byggingarleyfisgögnum liggur fyrir í verkgögnum (september 2025)."),
  ("Yfirlýsingar við verklok",
   "Við verklok fylgja kaflanum: staðfesting byggingarfulltrúa um að tilskildar áfangaúttektir hafi farið fram ásamt athugasemdum hans ef einhverjar eru; undirrituð yfirlýsing byggingarstjóra um verklok; og undirritaðar yfirlýsingar allra iðnmeistara um að þeirra verkhluta sé lokið skv. ákvæðum byggingarreglugerðar. Sniðmát yfirlýsinga og söfnunarskrá eru í vinnslu núna — söfnun hefst meðan iðnmeistarar eru enn á verkstað.")],
 "K4": [
  ("Efnissamþykktaferlið",
   "Byggingarvörur og tæknibúnaður fara í gegnum formlegt efnissamþykktaferli (submittals) í Procore: verktaki leggur fram tæknigögn vörunnar og hönnuður viðkomandi fagsviðs rýnir og samþykkir. Skráðar eru 264 efnissamþykktir (þar af 261 afgreidd) og eru fylgiskjöl þeirra — CE-vottorð, samræmisyfirlýsingar (DoP), tækniblöð og leiðbeiningar, alls 444 skjöl — spegluð í gagnasafn handbókarinnar og leitarbær í fullri textaleit."),
  ("CE-vottorðaskrá",
   "Úr fylgiskjölunum er unnin CE-vottorðaskrá kaflans skv. staðalformi FSRE, tafla 3: vara → tegund → söluaðili → framleiðandi → fylgiskjöl (tækniupplýsingar, vottorð, förgunarleiðbeiningar) [flokkun í vinnslu]. Meðal lykilbúnaðar með samþykktum tæknigögnum eru KONE MonoSpace 700DX lyftur, Televik sjúkrakallkerfi (Öryggismiðstöðin), álhurðir og gluggar frá BYKO og reyklúgur; einingatengdar vörur (stál, festingar, klæðningar) eru vottaðar í VBC-einingaskránni (K16). Förgunarleiðbeiningar verða teknar saman úr gögnum framleiðenda fyrir helstu efnisflokka.")],
 "K5": [
  ("Viðhald byggingarhluta",
   "Kaflinn tekur saman eftirlits-, viðhalds- og endingarupplýsingar helstu byggingarhluta: ytra byrðis og klæðninga VBC-eininga, stálþaks, glugga og útihurða (ál, BYKO), innveggja og loftaklæðninga (flokkur K210 B-s1,d0 skv. brunahönnun) og gólfefna (Dfl-s1; gólfílögn og gólfefni koma að mestu úr verksmiðju VBC). Fyrir hvern byggingarhluta verður tilgreint: eftirlitstíðni, viðhaldsaðgerðir, áætluð ending og tilvísun í gögn framleiðanda."),
  ("Heimildir og söfnun",
   "Gögn framleiðenda úr efnissamþykktum (K4) mynda grunninn og er heimilt skv. staðalformi FSRE að nota leiðbeiningar framleiðanda beint sem hluta handbókar. Sérstakar viðhaldsleiðbeiningar fyrir einingabygginguna — klæðningar, þéttingar milli eininga, festingar — verða sóttar til VBC meðan framleiðandi er enn virkur í verkinu [í gangi — sjá gátlista].")],
 "K6": [
  ("Kerfislýsing raflagna (drög)",
   "Raflagnir eru skv. verklýsingu Verkhönnunar (Hringhamar 43, kafli 4). Kerfið samanstendur af heimtaug og aðaltöflu, töfluskápum hæða/deilda (einlínumyndir TG1.1, TG4.1 o.fl. í teikningasafni), almennri raflögn og lýsingu (lýsingarhönnun ARKÍS), neyðarlýsingu skv. ÍST EN 1838 og ÍST EN 50172 (1 lúx á flóttaleiðum og göngum, 0,5 lúx í opnum rýmum yfir 60 m²), út-ljósum og leiðarmerkingum, og vararafli fyrir rafdrifnar hurðir í flóttaleið [staðfesta: umfang varaafls og aðrar neyðarrásir]. Rafdrifnar rennihurðir aðalinngangs eru vaktar af brunaviðvörunarkerfi og opnast með handboða í neyð. Netlagnir og netbúnaður eru frá Origo. Raflagnir innan eininga eru lagðar í verksmiðju VBC skv. rafbúnaðarforskrift framleiðslusamningsins (4000 - Electrical Equipment Guidelines); verktaki á staðnum tengir milli eininga og við stofnkerfi."),
  ("Prófanir og skil",
   "Við gangsetningu skilar rafvirkjameistari undirritaðum prófunar- og úttektarvottorðum raforkuvirkis og neysluveituskýrslu; staðfesting HMS á móttöku hennar fylgir kaflanum. Yfirlit orkumæla (staðsetning og álestur) verður merkt af teikningum [í vinnslu]. Lýsing á hagkvæmri stýringu kerfa m.t.t. orkunotkunar færist í K19 rekstraráætlun.")],
 "K7": [
  ("Kerfislýsing lagnakerfa (drög)",
   "Lagnakerfi eru skv. verklýsingu TEKNIK nr. 24-085, kafla 3. Hitakerfi: stofnlagnir hitakerfis, snjóbræðslukerfis og að hiturum loftræsikerfis, með tengigrindum, lokum, mælum og búnaði skv. teikningum; lagnir innan rýmiseininga eru lagðar í verksmiðju VBC og verktaki á staðnum (Rennsli ehf.) tengir við stofnlagnir á göngum og í lagnaklefum. Neysluvatnslagnir (heitt og kalt) eru sama fyrirkomulags. Fráveitulagnir og regnvatnslagnir liggja í grunn og að fráveitukerfi bæjarins; lagnir í jörðu voru verkhluti jarðvinnu og hafa hlotið áfangaúttektir (stafliðir q, r, o, u gr. 3.7.4). Brunaþéttingar meðfram lögnum eru skv. kafla 3.6 verklýsingar."),
  ("Prófanir og skil",
   "Þrýstiprófanir, skolun og stillingar kerfa fara fram við gangsetningu með undirrituðum staðfestingum pípulagningameistara á prófun og stillingu skv. verklýsingu hönnuðar (gr. 3.0.2 og 3.5.7 gera kröfu um úttektir og rekstrarhandbók lagnakerfa — það efni rennur beint inn í þennan kafla). Yfirlit vatnsmæla, aðalloka og snjóbræðslustýringar verður merkt af teikningum [í vinnslu].")],
 "K8": [
  ("Kerfislýsing loftræsikerfis (drög)",
   "Loftræsing er skv. verklýsingu TEKNIK 24-085, kafla 3.7, og loftræsiteikningum fyrir hverja hæð (teikningaröð 26.xx). Kerfið samanstendur af loftræsisamstæðum með hiturum og stjórnbúnaði (gr. 3.7.7) [staðfesta: fjöldi og staðsetning samstæðva í tæknirými], stokkakerfi úr galvanhúðuðu stáli með einangrun og gaumlúgum, dreifurum/ristum/ventlum, bruna- og reyklokum (gr. 3.7.4) og loftinntökum/útköstum (gr. 3.7.6). Nemar í stokkum (gr. 3.7.8) tengjast stjórnkerfi. Loftmagnsútreikningar fyrir einingarnar liggja fyrir í forskrift framleiðslusamnings VBC. Verktaki loftræsingar á staðnum er Ísloft blikk- og stálsmiðja ehf."),
  ("Stilling og úttekt",
   "Skv. gr. 3.7.9 verklýsingar og h-lið HMS-leiðbeininga fylgir kaflanum sameiginleg, undirrituð skýrsla hönnuðar og blikksmíða-, pípulagninga- og rafvirkjameistara um að kerfið sé stillt skv. hönnunarforskrift, með niðurstöðum loftmagnsmælinga borið saman við hönnunargildi, stillingum og prófun alls búnaðar ásamt samvirkniprófun tækja. Prófunin verður bókuð tímanlega fyrir öryggisúttekt og skýrslusniðmát undirbúið fyrirfram. Merkingar kerfa eru skv. gr. 3.7.10.")],
 "K9": [
  ("Brunavarnir hússins",
   "Brunavarnir eru skv. brunahönnun ÖRUGG verkfræðistofu nr. 3749-001-SKY-001 (samantekt 3749-001-SAT-001-V02, dags. 26.9.2025). Byggingin er hjúkrunarheimili í notkunarflokki 5; brunaálag skal vera undir 800 MJ/m² [samræma hámarksfjölda íbúa (88 í V02) við lokaútfærslu rýma]. Allar vegg- og loftaklæðningar eru í flokki K210 B-s1,d0 (flokkur 1); niðurhengd loft og hljóðdempunarplötur í flokki B-s1,d0; gólfefni Dfl-s1 en Cfl-s1 í stigahúsum."),
  ("Brunaviðvörunar- og slökkvikerfi",
   "Brunaviðvörunarkerfi skv. ÍST EN 54 er í allri byggingunni, tengt viðurkenndri vaktstöð skv. leiðbeiningum HMS; brunastöð er í aðalinngangi og undirstöðvar á hæðum til upplýsinga fyrir starfsfólk. Kerfið vaktar vatnsúðakerfið og stýrir reyklúgum í lyftustokkum. Húsið er allt varið vatnsúðakerfi skv. ÍST EN 12845 ásamt fylgiritum; sprinklerklefi er á jarðhæð, aðgengilegur utan frá, með inndælingartengi og vatnsbjöllu á útvegg; áhættuflokkun kerfisins er skv. brunahönnunarskýrslu. Handslökkvitæki eru skv. ÍST EN 3: 6L léttvatnstæki (21A/183B) almennt og 5 kg CO2-tæki í tæknirýmum; slöngukefli eru ekki í byggingunni. Þurrar stigleiðslur með lokum og tengingum slökkviliðs á hverri hæð eru í öllum stigahúsum (gr. 9.8.5 byggingarreglugerðar) og tengibúnaður við dælur slökkviliðs á jarðhæð."),
  ("Reyklosun, neyðarlýsing og flóttaleiðir",
   "Reyklúgur skv. ÍST EN 12101-2 eru yfir lyftustokkum og opnast sjálfvirkt við staðfest brunaboð frá skynjara efst í lyftustokk. Aðalstigahús er með opnanlegu fagi (0,25 m²) á hverri hæð til reykræsingar og endastigahús eru opin/með netalokun; reyklosun er að öðru leyti um glugga og hurðir sem slökkvilið opnar. Neyðarlýsing skv. ÍST EN 1838/50172 er 1 lúx á flóttaleiðum og göngum, 0,5 lúx í opnum rýmum yfir 60 m² og í salernum og anddyrum íbúðarrýma. Mesta reiknuð lengd flóttaleiðar að útgangi eða inn í annað brunahólf er innan við 39 m. Hurðir í flóttaleiðum íbúa hafa neyðarhúna skv. ÍST EN 179 og hurðir að stigum og út neyðarslár skv. ÍST EN 1125; hurðir með aðgangsstýringu í flóttaleið hafa brotrofa („Neyðarútgangur — Brjótið glerið“) sem rýfur læsingu og gangsetur brunaviðvörunarkerfið."),
  ("Rýmingarstefna",
   "Fyrsta stig rýmingar byggingarinnar er lárétt á milli brunahólfa innan hæða — íbúar eru fluttir í næsta brunahólf á sömu hæð, ekki niður stiga. Gert er ráð fyrir að slökkvilið aðstoði við rýmingu af hæðum og niður. Rýmingu er stýrt af starfsfólki sem tryggir að enginn sé skilinn eftir á biðsvæðum. Rýmingaráætlun skv. reglum HMS og Vinnueftirlitsins skal sett upp fyrir töku í notkun og brunaæfingar haldnar reglulega (sjá K12 og B3)."),
  ("Prófanir og þjónustusamningar",
   "Fyrir öryggisúttekt þurfa að liggja fyrir prófunarniðurstöður brunaviðvörunar-, úða- og neyðarlýsingarkerfa, cause & effect samvirknilýsing [óskast frá ÖRUGG — sjá gátlista] og undirritaðir þjónustusamningar um brunaviðvörunarkerfi, úðakerfi og lyftur. Ákvörðun um hver gerir þjónustusamningana (eigandi/FSRE/Sóltún) er forsenduatriði og er á eltilistanum.")],
 "K10": [
  ("Lyftur",
   "Í byggingunni eru KONE MonoSpace 700DX fólkslyftur [staðfesta fjölda] skv. samþykktri efnissamþykkt (80-1/80-2 með teikningum); lyfturnar uppfylla kröfur gr. 3.9.9 byggingarreglugerðar um stærð og búnað fyrir hjúkrunarheimili. Reyklúgur eru yfir lyftustokkum og opnast við brunaboð (sjá K9). Við gangsetningu fylgja vottorð Vinnueftirlitsins, prófunarskýrslur og þjónustusamningur; lyftur eru háðar reglubundinni lögboðinni skoðun."),
  ("Vélknúnar hurðir",
   "Rafdrifnar rennihurðir aðalinngangs eru búnar vararafli sem brunaviðvörunarkerfið vaktar, og handboða sem opnar hurðina úr læstri stöðu í neyð. Aðrar vélknúnar hurðir [staðfesta umfang] fylgja sömu kröfum um prófanir og þjónustu."),
  ("Sjúkrakallkerfi",
   "Sjúkrakallkerfi hússins er Televik, birgir Öryggismiðstöðin (efnissamþykkt 0-01). Kerfið þjónar hjúkrunarrýmum, böðum og sameiginlegum rýmum [staðfesta útfærslu og umfang]. Ábyrgðarskil milli húss (lagnir, grunnkerfi) og rekstraraðila (endabúnaður, vöktun, þjónustusamningur) verða skilgreind fyrir afhendingu [í gangi — sjá gátlista]. Virknilýsing, prófanir og notendaleiðbeiningar fylgja við gangsetningu."),
  ("Annar sérhæfður búnaður",
   "Eldhús- og þvottahúsbúnaður: [staðfesta umfang í verkinu vs. búnað rekstraraðila; matarvagnar (client specified) eru meðal samþykkts búnaðar]. Netbúnaður og tæknirými upplýsingakerfa: Origo. Fyrir hvern búnaðarlið fylgja virknilýsing, prófanir, rekstrar- og viðhaldsleiðbeiningar og tengiliður þjónustu.")],
 "K11": [
  ("Gangsetningarmappa (commissioning)",
   "Úttektar- og prófanaferli verksins er skráð í Procore og myndar grunn gangsetningarmöppunnar: prófanir verktaka á kerfum, stillingar og loks undirritaðar viðtökuprófanir allra kerfa með tilvísun í þá staðla sem prófað er eftir (FSRE gr. 1.11). Samvirkniprófanir eru sérstakur þáttur: brunaviðvörun ↔ úðakerfi ↔ reyklúgur ↔ lyftur ↔ rafdrifnar hurðir ↔ loftræsing (bruna-/reyklokur) — cause & effect skjal brunahönnuðar er prófunargrunnurinn. Möppuskipan og prófunaráætlun verða sett upp haustið 2026 svo prófanir vetrarins skili sér beint inn í handbókina; niðurstöður renna jafnframt í K19 rekstraráætlun.")],
 "K12": [
  ("Fræðsla og þjálfun",
   "Fyrir afhendingu fær starfsfólk rekstraraðila (Sóltún) og eftir atvikum FSRE þjálfun í notkun og rekstri kerfa hússins: brunaviðvörunarkerfi og viðbrögð við brunaboði, sjúkrakallkerfi (Televik), hússtjórnarkerfi og hitastýring, loftræsing, lyftur, aðgangskerfi, eldhús- og þvottahúsbúnaður, flokkun úrgangs og umhverfisvæn efnisnotkun við viðhald. Þjálfunaráætlun verður unnin með Sóltúni nær afhendingu; staðfestingar þátttakenda með undirskriftum og fræðsluefni (þ.m.t. upptökur ef gerðar) varðveitast í þessum kafla. Brunaæfingar eru hluti þjálfunar og endurteknar reglulega í rekstri.")],
 "K13": [
  ("Öryggi, heilsa og umhverfi",
   "Áhættugreiningar verksins eru varðveittar í verkgagnagrunninum og úr þeim verður unnin eftirstöðvaáhættuskrá (residual hazards): þær hættur sem eftir standa í rekstri og viðhaldi hússins, öruggar viðhaldsaðferðir og þjónustuleiðir — m.a. þakvinna og fallvarnir á stálþaki, vinna í lyftustokkum, tæknirýmum og lagnaklefum, og vinna við rafbúnað. Hættuleg efni sem notuð voru í mannvirkinu verða skráð með tilvísun í vottorð og öryggisblöð úr efnissamþykktum (K4) ásamt leiðbeiningum um meðhöndlun og förgun. Tilkynning til Vinnueftirlits um byggingarframkvæmd og öryggisstjórnun verktíma er skjalfest í K15.")],
 "K14": [
  ("Aðgengi og samgöngur (drög)",
   "Hjúkrunarheimilið stendur við Hringhamar 43 í Hamraneshverfi í Hafnarfirði (landeignanúmer 1231987). Á lóð eru bílastæði fyrir gesti og starfsfólk skv. lóðaruppdrætti Landslags, þar af merkt stæði hreyfihamlaðra við aðalinngang, ásamt hjólastæðum [staðfesta fjölda; skyggni yfir hjólastæði gesta er til skoðunar]. Aðkoma sjúkraflutninga og vöruafhendingar er [staðfesta af lóðaruppdrætti]. Almenningssamgöngur: [staðfesta strætóleið og næstu stöð]. Byggingin er hönnuð skv. algildri hönnun: þrepalaus aðkoma, sjálfvirkar inngangshurðir, lyftur á allar hæðir og aðgengileg salerni; öryggismál gesta (móttaka, aðgangsstýring) eru rakin hér.")],
 "K15": [
  ("Vottorð og skjöl",
   "Í kaflanum eru varðveitt skv. staðalformi FSRE og leiðbeiningu MVS 4.10.12: löggildingar allra iðnmeistara; skrá yfir staðla sem kerfi voru prófuð eftir; ábyrgðaryfirlýsingar hönnuða og byggingarstjóra vegna byggingarleyfa; tilkynningar um iðnmeistara- eða byggingarstjóraskipti [staðfesta hvort einhver urðu]; tilkynning til Vinnueftirlits um byggingarframkvæmd; úttektarvottorð opinberra aðila (byggingarfulltrúi, slökkvilið, Vinnueftirlit, heilbrigðiseftirlit) eftir því sem þau falla til; og rýni byggingarfulltrúa á byggingarleyfisgögnum (fyrirliggjandi, sept. 2025). Söfnun stendur yfir samhliða yfirlýsingasöfnun K3.")],
 "K16": [
  ("Einingabyggingin",
   "Húsið er sett saman úr forsmíðuðum rýmiseiningum framleiddum af VBC [staðfesta framleiðslustað]; burðarvirki eininga er hannað af WSP og stálvirki framleitt af Norvik Group (verkstæðisteikningar í teikningasafni: burðargrindur, festiplötur, þakeiningar). Einingarnar koma langt frágengnar úr verksmiðju: gólfílögn og gólfefni, innréttingar, raflagnir skv. rafbúnaðarforskrift og lagnir sem verktakar á staðnum tengja við stofnkerfi á göngum. Samsetning og þétting á verkstað (zip-up) er á hendi áhafna VBC. Afhending fer fram í tveimur meginlotum: lota 1 (50 einingar) september 2026, lota 2 frá viku 12. október 2026. Framleiðslusamningurinn með viðaukum (hönnunarforskriftir, rafbúnaðar- og lagnaforskriftir, loftmagnsútreikningar) er varðveittur í verkgagnagrunninum."),
  ("Gæðaskjöl hverrar einingar",
   "Fyrir hverja einingu fylgir QC-pakki úr verksmiðju (as-built documentation): efnisvottorð skv. EN 10204 3.1, efnislistar, suðuskrár, skrá suðumanna og suðuhæfnisvottorð, suðuvír/íhlutir, óeyðandi prófanir (VT sjónskoðun, MT segulagnaprófun, UT hljóðbylgjuprófun), CE-merking og samræmisyfirlýsing (DoP), mælingakort, viðtökuvottorð (acceptance protocol/report), verkskrá (protocol of works) og kvörðunarvottorð mælitækja. Á fyrirtækjastigi fylgja vottanir framleiðanda (m.a. suðuferlar og NDT-hæfni). Skjölin eru spegluð í gagnasafnið og staða hverrar einingar birt í VBC-einingaskránni; 24 einingar eru skráðar með QC-pökkum og göt (3 einingar vantar stakar prófanaskýrslur) elt við VBC pr. lotu — sjá sjálfvirkan lista í gátlistanum."),
  ("Flutningur, rakavarnir og samsetning",
   "Einingar eru varðar fyrir raka í flutningi [staðfesta: umfang flutnings- og rakaskjala í spegli — óskað frá VBC; rakavarnarpokar voru til umfjöllunar í fyrirspurn á verktíma]. Samsetningar- og þéttiskrár af verkstað (zip-up) verða hluti kaflans þegar uppsetningu lýkur, ásamt úttektum á samsetningu og frágangi tenginga milli eininga (burðarvirki, lagnir, raflagnir, brunaþéttingar).")],
 "K17": [
  ("Hússtjórnarkerfi (drög)",
   "Stýringar hússins ná til loftræsisamstæðva (hitarar, loftmagn, nemar í stokkum), hitakerfis og snjóbræðslu um tengigrindur, og vöktunar tæknikerfa [staðfesta umfang miðlægs BMS-kerfis og stýriverktaka]. Skjalfest verða: kerfisuppbygging, punktalistar, stýrisekvensar (sequences of operation), myndræn viðmót og notendaleiðbeiningar, ásamt netuppbyggingu tæknikerfa (Origo). Við afhendingu verða aðgangsorð, leyfi og hugbúnaðarlyklar afhentir formlega og skráðir hér; sekvensar og punktalistar eru jafnframt forsenda þess að viðtökuprófanir K11 verði prófanlegar. Gögnin verða sótt til stýriverktaka [í gangi — sjá gátlista].")],
 "K18": [
  ("Ábyrgðir og varahlutir",
   "Samræmt ábyrgðafylki verður unnið úr verksamningum í verkgagnagrunninum (Grafa og Grjót, Steypustöðin, Múrverk og Slípun, Rennsli, Ísloft, Heildarverk, Steingarður, VBC/Norvik, KONE, BYKO o.fl.): atriði, ábyrgðaraðili, upphafstími (frá afhendingu/úttekt), ábyrgðartími, skilyrði (t.d. þjónustusamningur í gildi og reglubundið viðhald skv. K5) og tengiliður krafna. Beinagrind fylkisins er unnin nú; fyllt við verklok. Varahlutir, sérverkfæri, lyklar og umframefni sem fylgja húsinu verða skráð við afhendingu ásamt geymslustað.")],
 "K19": [
  ("Rekstraráætlun (drög)",
   "Kaflinn dregur saman rekstrarstillingar hússins: stillipunkta og keyrslutíma kerfa (úr niðurstöðum gangsetningar), orkumarkmið og eftirfylgni m.v. BREEAM-viðmið, yfirlit aðalloka og rofa — lokunarstaðir neysluvatns, hitaveitu, snjóbræðslu og rafmagns, merkt af teikningum [í vinnslu] — og neyðarferla við leka, rafmagnsleysi og kerfisbilanir með tengiliðum þjónustuaðila. Lýsing á hagkvæmri stýringu kerfa m.t.t. fjárhagslegs ávinnings og umhverfis (krafa FSRE gr. 1.6/1.7) byggir á sekvensum K17. Rekstrarefni fyrir daglega notendur er í Handbók B; hér er tæknilega viðmiðið.")],
}

EFNI_B = {
 "B1": "Húsið er hjúkrunarheimili með 96 hjúkrunarrýmum [staðfesta lokafjölda] í eigu Hjúkrunarheimilisins Hamranesi ehf., leigt FSRE til 25 ára og rekið af Sóltúni. Þar til lokaúttekt lýkur fer byggingarstjóri (Hallgrímur Magnússon, Ísfast) með innra eftirlit eiganda. Verkaskipting í rekstri — hver sér um viðhald húss, kerfa og búnaðar, hver tekur við bilanatilkynningum og hver ber kostnað — fylgir leigusamningi FSRE [skiptifylki í vinnslu]. Tengiliðalisti með símanúmerum utan dagvinnutíma verður hér, þ.m.t. vaktstöð brunaviðvörunar, lyftuþjónusta (KONE) og lagna-/rafmagnsvakt.",
 "B2": "Leiðbeiningar fyrir daglega notkun: hita- og birtustýringar í rýmum, aðgangskerfi og læsingar, grunnatriði sjúkrakallkerfisins (Televik), notkun lyfta, og sérrými (eldhús, þvottahús, fjölnotasalur, sameign). Efnið verður unnið upp úr notendaleiðbeiningum kerfanna (K6–K10) þegar þau eru gangsett — hagnýtt, myndskreytt og án tæknimáls, á íslensku.",
 "B3": "Við brunaboð: brunaviðvörunarkerfið er sítengt vaktstöð sem kallar út slökkvilið — starfsfólk fylgir rýmingaráætlun. Fyrsta stig rýmingar er lárétt: íbúar eru fluttir í næsta brunahólf á sömu hæð, ekki niður stiga; slökkvilið aðstoðar við rýmingu af hæðum. Starfsfólk tryggir að enginn verði eftir á biðsvæðum. Brunastöðin er í aðalinngangi og undirstöðvar á hæðum sýna hvaðan boðið kemur. Rennihurðir aðalinngangs opnast með handboða í neyð; hurðir með aðgangsstýringu í flóttaleið hafa brotrofa. Slökkvitæki eru 6L léttvatnstæki í almennum rýmum (staðsetningar á teikningum). Rýmingaráætlun skv. reglum HMS og Vinnueftirlitsins skal hanga uppi og brunaæfingar haldnar reglulega. Vatnsleki: aðallokar eru [staðfesta staðsetningu — merkt í K19]. Rafmagnsleysi: [staðfesta varaafl og viðbrögð]. Lyftubilun með innilokun: neyðarsími í lyftu tengist þjónustuaðila (KONE).",
 "B4": "Yfirlit orkukerfa hússins: hitaveita (hitakerfi, snjóbræðsla), rafmagn og loftræsing með varmaendurvinnslu [staðfesta]. Orkumarkmið fylgja BREEAM-viðmiðum verksins. Staðsetning orku- og vatnsmæla og hvernig lesið er af þeim verður sýnd hér (úr K6/K7). Kælimiðlar ef við á [staðfesta] eru skráðir með magni og þjónustukröfum.",
 "B5": "Vatnsstjórnun (heitt/kalt vatn, lokar, hitastig neysluvatns), úrgangsflokkar og losunarleiðir hjúkrunarheimilis (almennt sorp, endurvinnsla, lífrænt, áhættuúrgangur eftir reglum heilbrigðiseftirlits), þrifareglur og meðferð yfirborða: gólfefni (verksmiðjulagt vinyl/dúkar — hreinsiefni skv. leiðbeiningum framleiðanda), innréttingar og sérrými. Unnið úr viðhaldsgögnum K5 og kröfum rekstraraðila.",
 "B6": "Húsið stendur við Hringhamar 43 í Hamraneshverfi, Hafnarfirði. Bílastæði gesta og starfsfólks eru á lóð, merkt stæði hreyfihamlaðra við aðalinngang, hjólastæði við [staðfesta]. Vöruafhending og aðkoma sjúkraflutninga: [staðfesta af lóðaruppdrætti Landslags]. Almenningssamgöngur: [staðfesta leið og stöð]. Byggingin er með algildu aðgengi: þrepalaus aðkoma, sjálfvirkar inngangshurðir, lyftur á allar hæðir og aðgengileg salerni.",
 "B7": "Áður en ráðist er í breytingar á húsnæðinu — burðarveggir, lagnir, loftræsing, brunahólfun, festingar í einingaveggi og loft — skal leita samráðs við hönnuði hússins og upplýsa eiganda; breytingar á brunahólfun eða flóttaleiðum eru óheimilar án samþykkis byggingarfulltrúa. Sérstaða einingabyggingar: veggir og loft eru hluti burðarvirkis og þéttikerfis eininga — reglur um festingar og göt [staðfesta frá VBC] verða hér. Öll göt gegnum brunahólfandi skil skulu brunaþéttast af fagaðila og skráð.",
 "B8": "Árlegt viðhalds- og skoðanadagatal eiganda: lögboðnar skoðanir (brunaviðvörunarkerfi og vaktstöðvartenging, úðakerfi, lyftur — skoðun Vinnueftirlits, neyðarlýsing, reyklúgur), árstíðabundið viðhald (þakbrunnir og niðurföll, loftsíuskipti, snjóbræðslustýring fyrir vetur, þéttingar og frágangur útihurða) og ábyrgðarskilyrði sem krefjast reglubundinnar þjónustu (sjá K18). Dregið saman úr Handbók A við frystingu v1.0.",
 "B9": "Sérkafli hjúkrunarheimilis: eftirlitsaðilar velferðargeirans — heilbrigðiseftirlit (matvæli, þrif, úrgangur), embætti landlæknis (starfsleyfi rekstraraðila), Vinnueftirlit (vinnuvernd, lyftur og tæki) — og hvað hver skoðar; þjálfunarskrár starfsfólks Sóltúns (sjá K12); skyldufylki leigusamnings FSRE (eigandi vs. leigutaki vs. rekstraraðili) [unnið með Sóltúni og FSRE nær afhendingu]. Sjúkrakallkerfið (Televik/Öryggismiðstöðin) og þjónusta þess er lykilkerfi þessa kafla.",
 "B10": "Eigandi handbókarinnar eftir afhendingu er [eigandi/FSRE — staðfesta í afhendingarferli]; handbókin skal yfirfarin á 6 mánaða fresti fyrsta árið og árlega eftir það (BSRIA-viðmið). Breytingaskrá með útgáfum, dagsetningum og ábyrgðarmanni er haldin hér. Vefútgáfan og gagnagrunnurinn að baki henni fylgja með í afhendingu [útfærsla ákveðin við afhendingu].",
}
